server:
  port: 8083
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:sqlite:game.db
    driver-class-name: org.sqlite.JDBC